[2025-08-03 18:33:19 +0000] [16610] [INFO] Starting gunicorn 21.2.0
[2025-08-03 18:33:19 +0000] [16610] [INFO] Listening at: http://127.0.0.1:5004 (16610)
[2025-08-03 18:33:19 +0000] [16610] [INFO] Using worker: sync
[2025-08-03 18:33:19 +0000] [16611] [INFO] Booting worker with pid: 16611
[2025-08-03 18:33:19 +0000] [16612] [INFO] Booting worker with pid: 16612
[2025-08-03 18:33:19 +0000] [16613] [INFO] Booting worker with pid: 16613
[2025-08-03 18:33:19 +0000] [16614] [INFO] Booting worker with pid: 16614
[2025-08-03 18:33:49 +0000] [16610] [CRITICAL] WORKER TIMEOUT (pid:16611)
[2025-08-03 18:33:49 +0000] [16610] [CRITICAL] WORKER TIMEOUT (pid:16612)
[2025-08-03 18:33:49 +0000] [16610] [CRITICAL] WORKER TIMEOUT (pid:16613)
[2025-08-03 18:33:49 +0000] [16610] [CRITICAL] WORKER TIMEOUT (pid:16614)
[2025-08-03 18:33:49 +0000] [16614] [INFO] Worker exiting (pid: 16614)
[2025-08-03 18:33:49 +0000] [16613] [INFO] Worker exiting (pid: 16613)
[2025-08-03 18:33:49 +0000] [16611] [INFO] Worker exiting (pid: 16611)
[2025-08-03 18:33:50 +0000] [16610] [ERROR] Worker (pid:16611) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 18:33:50 +0000] [16610] [ERROR] Worker (pid:16614) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 18:33:50 +0000] [16610] [ERROR] Worker (pid:16613) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 18:33:50 +0000] [16610] [ERROR] Worker (pid:16612) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 18:33:50 +0000] [16631] [INFO] Booting worker with pid: 16631
[2025-08-03 18:33:50 +0000] [16632] [INFO] Booting worker with pid: 16632
[2025-08-03 18:33:50 +0000] [16633] [INFO] Booting worker with pid: 16633
[2025-08-03 18:33:50 +0000] [16634] [INFO] Booting worker with pid: 16634
[2025-08-03 18:34:21 +0000] [16610] [CRITICAL] WORKER TIMEOUT (pid:16631)
[2025-08-03 18:34:21 +0000] [16610] [CRITICAL] WORKER TIMEOUT (pid:16632)
[2025-08-03 18:34:21 +0000] [16610] [CRITICAL] WORKER TIMEOUT (pid:16633)
[2025-08-03 18:34:21 +0000] [16610] [CRITICAL] WORKER TIMEOUT (pid:16634)
[2025-08-03 18:34:22 +0000] [16633] [INFO] Worker exiting (pid: 16633)
[2025-08-03 18:34:22 +0000] [16610] [ERROR] Worker (pid:16631) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 18:34:22 +0000] [16610] [ERROR] Worker (pid:16633) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 18:34:22 +0000] [16610] [ERROR] Worker (pid:16634) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 18:34:22 +0000] [16610] [ERROR] Worker (pid:16632) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 18:34:22 +0000] [16639] [INFO] Booting worker with pid: 16639
[2025-08-03 18:34:22 +0000] [16640] [INFO] Booting worker with pid: 16640
[2025-08-03 18:34:22 +0000] [16641] [INFO] Booting worker with pid: 16641
[2025-08-03 18:34:22 +0000] [16642] [INFO] Booting worker with pid: 16642
[2025-08-03 19:00:21 +0000] [16641] [ERROR] Error handling request /dashboard
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/app.py", line 656, in dashboard
    return render_template('dashboard.html', cursos=cursos, mis_ventas=mis_ventas, cursos_comprados_ids=cursos_comprados_ids, cursos_pendientes_ids=cursos_pendientes_ids, current_time=current_time)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ubuntu/cursos/templates/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ubuntu/cursos/templates/base.html", line 85, in top-level template code
    {% include "shared/navbar.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/templates/shared/navbar.html", line 101, in top-level template code
    <a href="{{ url_for('login') }}" class="btn-ghost-gradient">Iniciar Sesi√≥n</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'actualizar_progreso_seccion' instead?
[2025-08-03 19:02:29 +0000] [16641] [INFO] Worker exiting (pid: 16641)
[2025-08-03 19:02:29 +0000] [16610] [INFO] Handling signal: term
[2025-08-03 19:02:29 +0000] [16640] [INFO] Worker exiting (pid: 16640)
[2025-08-03 19:02:29 +0000] [16639] [INFO] Worker exiting (pid: 16639)
[2025-08-03 19:02:29 +0000] [16610] [ERROR] Worker (pid:16641) was sent SIGTERM!
[2025-08-03 19:02:29 +0000] [16642] [INFO] Worker exiting (pid: 16642)
[2025-08-03 19:02:43 +0000] [16610] [INFO] Shutting down: Master
[2025-08-03 19:02:44 +0000] [17009] [INFO] Starting gunicorn 21.2.0
[2025-08-03 19:02:44 +0000] [17009] [INFO] Listening at: http://127.0.0.1:5004 (17009)
[2025-08-03 19:02:44 +0000] [17009] [INFO] Using worker: sync
[2025-08-03 19:02:44 +0000] [17010] [INFO] Booting worker with pid: 17010
[2025-08-03 19:02:44 +0000] [17011] [INFO] Booting worker with pid: 17011
[2025-08-03 19:02:44 +0000] [17012] [INFO] Booting worker with pid: 17012
[2025-08-03 19:02:44 +0000] [17013] [INFO] Booting worker with pid: 17013
[2025-08-03 19:03:15 +0000] [17009] [CRITICAL] WORKER TIMEOUT (pid:17010)
[2025-08-03 19:03:15 +0000] [17009] [CRITICAL] WORKER TIMEOUT (pid:17011)
[2025-08-03 19:03:15 +0000] [17009] [CRITICAL] WORKER TIMEOUT (pid:17012)
[2025-08-03 19:03:15 +0000] [17009] [CRITICAL] WORKER TIMEOUT (pid:17013)
[2025-08-03 19:03:16 +0000] [17009] [ERROR] Worker (pid:17010) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 19:03:16 +0000] [17009] [ERROR] Worker (pid:17011) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 19:03:16 +0000] [17009] [ERROR] Worker (pid:17012) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 19:03:16 +0000] [17009] [ERROR] Worker (pid:17013) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 19:03:16 +0000] [17022] [INFO] Booting worker with pid: 17022
[2025-08-03 19:03:16 +0000] [17023] [INFO] Booting worker with pid: 17023
[2025-08-03 19:03:16 +0000] [17024] [INFO] Booting worker with pid: 17024
[2025-08-03 19:03:16 +0000] [17025] [INFO] Booting worker with pid: 17025
[2025-08-03 19:03:46 +0000] [17009] [CRITICAL] WORKER TIMEOUT (pid:17022)
[2025-08-03 19:03:46 +0000] [17009] [CRITICAL] WORKER TIMEOUT (pid:17023)
[2025-08-03 19:03:46 +0000] [17009] [CRITICAL] WORKER TIMEOUT (pid:17024)
[2025-08-03 19:03:46 +0000] [17009] [CRITICAL] WORKER TIMEOUT (pid:17025)
[2025-08-03 19:03:46 +0000] [17024] [INFO] Worker exiting (pid: 17024)
[2025-08-03 19:03:46 +0000] [17022] [INFO] Worker exiting (pid: 17022)
[2025-08-03 19:03:46 +0000] [17023] [INFO] Worker exiting (pid: 17023)
[2025-08-03 19:03:46 +0000] [17025] [INFO] Worker exiting (pid: 17025)
[2025-08-03 19:03:47 +0000] [17009] [ERROR] Worker (pid:17023) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 19:03:47 +0000] [17009] [ERROR] Worker (pid:17024) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 19:03:47 +0000] [17009] [ERROR] Worker (pid:17025) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 19:03:47 +0000] [17009] [ERROR] Worker (pid:17022) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 19:03:48 +0000] [17034] [INFO] Booting worker with pid: 17034
[2025-08-03 19:03:48 +0000] [17035] [INFO] Booting worker with pid: 17035
[2025-08-03 19:03:48 +0000] [17036] [INFO] Booting worker with pid: 17036
[2025-08-03 19:03:48 +0000] [17037] [INFO] Booting worker with pid: 17037
[2025-08-03 19:04:18 +0000] [17009] [CRITICAL] WORKER TIMEOUT (pid:17036)
[2025-08-03 19:04:18 +0000] [17009] [CRITICAL] WORKER TIMEOUT (pid:17037)
[2025-08-03 19:04:19 +0000] [17036] [INFO] Worker exiting (pid: 17036)
[2025-08-03 19:04:19 +0000] [17037] [INFO] Worker exiting (pid: 17037)
[2025-08-03 19:04:19 +0000] [17009] [ERROR] Worker (pid:17037) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 19:04:19 +0000] [17009] [ERROR] Worker (pid:17036) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 19:04:19 +0000] [17048] [INFO] Booting worker with pid: 17048
[2025-08-03 19:04:19 +0000] [17047] [INFO] Booting worker with pid: 17047
[2025-08-03 19:05:12 +0000] [17048] [ERROR] Error handling request /dashboard
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/app.py", line 656, in dashboard
    return render_template('dashboard.html', cursos=cursos, mis_ventas=mis_ventas, cursos_comprados_ids=cursos_comprados_ids, cursos_pendientes_ids=cursos_pendientes_ids, current_time=current_time)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ubuntu/cursos/templates/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ubuntu/cursos/templates/base.html", line 85, in top-level template code
    {% include "shared/navbar.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/templates/shared/navbar.html", line 101, in top-level template code
    <a href="{{ url_for('login') }}" class="btn-ghost-gradient">Iniciar Sesi√≥n</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'actualizar_progreso_seccion' instead?
[2025-08-03 20:48:48 +0000] [17034] [ERROR] Error handling request /dashboard
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/app.py", line 656, in dashboard
    return render_template('dashboard.html', cursos=cursos, mis_ventas=mis_ventas, cursos_comprados_ids=cursos_comprados_ids, cursos_pendientes_ids=cursos_pendientes_ids, current_time=current_time)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ubuntu/cursos/templates/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ubuntu/cursos/templates/base.html", line 85, in top-level template code
    {% include "shared/navbar.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/templates/shared/navbar.html", line 101, in top-level template code
    <a href="{{ url_for('login') }}" class="btn-ghost-gradient">Iniciar Sesi√≥n</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'actualizar_progreso_seccion' instead?
[2025-08-03 20:49:04 +0000] [17034] [ERROR] Error handling request /dashboard
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/app.py", line 656, in dashboard
    return render_template('dashboard.html', cursos=cursos, mis_ventas=mis_ventas, cursos_comprados_ids=cursos_comprados_ids, cursos_pendientes_ids=cursos_pendientes_ids, current_time=current_time)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ubuntu/cursos/templates/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ubuntu/cursos/templates/base.html", line 85, in top-level template code
    {% include "shared/navbar.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/templates/shared/navbar.html", line 101, in top-level template code
    <a href="{{ url_for('login') }}" class="btn-ghost-gradient">Iniciar Sesi√≥n</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'actualizar_progreso_seccion' instead?
[2025-08-03 20:50:45 +0000] [17048] [ERROR] Error handling request /dashboard
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/app.py", line 656, in dashboard
    return render_template('dashboard.html', cursos=cursos, mis_ventas=mis_ventas, cursos_comprados_ids=cursos_comprados_ids, cursos_pendientes_ids=cursos_pendientes_ids, current_time=current_time)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ubuntu/cursos/templates/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ubuntu/cursos/templates/base.html", line 85, in top-level template code
    {% include "shared/navbar.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/templates/shared/navbar.html", line 101, in top-level template code
    <a href="{{ url_for('login') }}" class="btn-ghost-gradient">Iniciar Sesi√≥n</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'actualizar_progreso_seccion' instead?
[2025-08-03 21:03:04 +0000] [17034] [INFO] Worker exiting (pid: 17034)
[2025-08-03 21:03:04 +0000] [17048] [INFO] Worker exiting (pid: 17048)
[2025-08-03 21:03:04 +0000] [17035] [INFO] Worker exiting (pid: 17035)
[2025-08-03 21:03:04 +0000] [17047] [INFO] Worker exiting (pid: 17047)
[2025-08-03 21:03:04 +0000] [17009] [INFO] Handling signal: term
[2025-08-03 21:03:04 +0000] [17009] [ERROR] Worker (pid:17035) was sent SIGTERM!
[2025-08-03 21:03:04 +0000] [17009] [ERROR] Worker (pid:17047) was sent SIGTERM!
[2025-08-03 21:03:04 +0000] [17009] [ERROR] Worker (pid:17048) was sent SIGTERM!
[2025-08-03 21:03:04 +0000] [17009] [ERROR] Worker (pid:17034) was sent SIGTERM!
[2025-08-03 21:03:04 +0000] [17009] [INFO] Shutting down: Master
[2025-08-03 21:03:05 +0000] [19414] [INFO] Starting gunicorn 21.2.0
[2025-08-03 21:03:05 +0000] [19414] [INFO] Listening at: http://127.0.0.1:5004 (19414)
[2025-08-03 21:03:05 +0000] [19414] [INFO] Using worker: sync
[2025-08-03 21:03:05 +0000] [19415] [INFO] Booting worker with pid: 19415
[2025-08-03 21:03:05 +0000] [19416] [INFO] Booting worker with pid: 19416
[2025-08-03 21:03:05 +0000] [19417] [INFO] Booting worker with pid: 19417
[2025-08-03 21:03:05 +0000] [19418] [INFO] Booting worker with pid: 19418
[2025-08-03 21:03:35 +0000] [19415] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/cursos/wsgi.py", line 16, in <module>
    init_app()
  File "/home/ubuntu/cursos/app.py", line 176, in init_app
    init_routes(app)
  File "/home/ubuntu/cursos/routes/__init__.py", line 7, in init_routes
    AuthRoutes(app)
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 14, in __init__
    self.init_routes()
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 17, in init_routes
    @self.app.route('/register', methods=['GET', 'POST'])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 364, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 44, in wrapper_func
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/app.py", line 659, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: register
[2025-08-03 21:03:35 +0000] [19415] [INFO] Worker exiting (pid: 19415)
[2025-08-03 21:03:36 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19415)
[2025-08-03 21:03:36 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19416)
[2025-08-03 21:03:36 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19417)
[2025-08-03 21:03:36 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19418)
[2025-08-03 21:03:37 +0000] [19414] [ERROR] Worker (pid:19415) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:03:37 +0000] [19414] [ERROR] Worker (pid:19417) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:03:37 +0000] [19414] [ERROR] Worker (pid:19418) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:03:37 +0000] [19414] [ERROR] Worker (pid:19416) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:03:37 +0000] [19451] [INFO] Booting worker with pid: 19451
[2025-08-03 21:03:37 +0000] [19452] [INFO] Booting worker with pid: 19452
[2025-08-03 21:03:37 +0000] [19453] [INFO] Booting worker with pid: 19453
[2025-08-03 21:03:37 +0000] [19454] [INFO] Booting worker with pid: 19454
[2025-08-03 21:04:06 +0000] [19453] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/cursos/wsgi.py", line 16, in <module>
    init_app()
  File "/home/ubuntu/cursos/app.py", line 176, in init_app
    init_routes(app)
  File "/home/ubuntu/cursos/routes/__init__.py", line 7, in init_routes
    AuthRoutes(app)
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 14, in __init__
    self.init_routes()
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 17, in init_routes
    @self.app.route('/register', methods=['GET', 'POST'])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 364, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 44, in wrapper_func
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/app.py", line 659, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: register
[2025-08-03 21:04:06 +0000] [19452] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/cursos/wsgi.py", line 16, in <module>
    init_app()
  File "/home/ubuntu/cursos/app.py", line 176, in init_app
    init_routes(app)
  File "/home/ubuntu/cursos/routes/__init__.py", line 7, in init_routes
    AuthRoutes(app)
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 14, in __init__
    self.init_routes()
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 17, in init_routes
    @self.app.route('/register', methods=['GET', 'POST'])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 364, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 44, in wrapper_func
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/app.py", line 659, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: register
[2025-08-03 21:04:06 +0000] [19451] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/cursos/wsgi.py", line 16, in <module>
    init_app()
  File "/home/ubuntu/cursos/app.py", line 176, in init_app
    init_routes(app)
  File "/home/ubuntu/cursos/routes/__init__.py", line 7, in init_routes
    AuthRoutes(app)
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 14, in __init__
    self.init_routes()
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 17, in init_routes
    @self.app.route('/register', methods=['GET', 'POST'])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 364, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 44, in wrapper_func
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/app.py", line 659, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: register
[2025-08-03 21:04:06 +0000] [19452] [INFO] Worker exiting (pid: 19452)
[2025-08-03 21:04:06 +0000] [19453] [INFO] Worker exiting (pid: 19453)
[2025-08-03 21:04:06 +0000] [19451] [INFO] Worker exiting (pid: 19451)
[2025-08-03 21:04:08 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19451)
[2025-08-03 21:04:08 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19452)
[2025-08-03 21:04:08 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19453)
[2025-08-03 21:04:08 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19454)
[2025-08-03 21:04:09 +0000] [19414] [ERROR] Worker (pid:19451) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:04:09 +0000] [19414] [ERROR] Worker (pid:19452) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:04:09 +0000] [19414] [ERROR] Worker (pid:19453) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:04:09 +0000] [19414] [ERROR] Worker (pid:19454) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:04:09 +0000] [19492] [INFO] Booting worker with pid: 19492
[2025-08-03 21:04:09 +0000] [19491] [INFO] Booting worker with pid: 19491
[2025-08-03 21:04:09 +0000] [19490] [INFO] Booting worker with pid: 19490
[2025-08-03 21:04:09 +0000] [19493] [INFO] Booting worker with pid: 19493
[2025-08-03 21:04:40 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19490)
[2025-08-03 21:04:40 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19491)
[2025-08-03 21:04:40 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19492)
[2025-08-03 21:04:40 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19493)
[2025-08-03 21:04:41 +0000] [19414] [ERROR] Worker (pid:19491) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:04:41 +0000] [19414] [ERROR] Worker (pid:19492) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:04:41 +0000] [19414] [ERROR] Worker (pid:19493) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:04:41 +0000] [19414] [ERROR] Worker (pid:19490) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:04:41 +0000] [19521] [INFO] Booting worker with pid: 19521
[2025-08-03 21:04:41 +0000] [19522] [INFO] Booting worker with pid: 19522
[2025-08-03 21:04:41 +0000] [19523] [INFO] Booting worker with pid: 19523
[2025-08-03 21:04:41 +0000] [19524] [INFO] Booting worker with pid: 19524
[2025-08-03 21:05:11 +0000] [19524] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/cursos/wsgi.py", line 16, in <module>
    init_app()
  File "/home/ubuntu/cursos/app.py", line 176, in init_app
    init_routes(app)
  File "/home/ubuntu/cursos/routes/__init__.py", line 7, in init_routes
    AuthRoutes(app)
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 14, in __init__
    self.init_routes()
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 17, in init_routes
    @self.app.route('/register', methods=['GET', 'POST'])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 364, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 44, in wrapper_func
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/app.py", line 659, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: register
[2025-08-03 21:05:11 +0000] [19524] [INFO] Worker exiting (pid: 19524)
[2025-08-03 21:05:12 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19521)
[2025-08-03 21:05:12 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19522)
[2025-08-03 21:05:12 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19523)
[2025-08-03 21:05:12 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19524)
[2025-08-03 21:05:12 +0000] [19522] [INFO] Worker exiting (pid: 19522)
[2025-08-03 21:05:12 +0000] [19523] [INFO] Worker exiting (pid: 19523)
[2025-08-03 21:05:12 +0000] [19521] [INFO] Worker exiting (pid: 19521)
[2025-08-03 21:05:13 +0000] [19414] [ERROR] Worker (pid:19521) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:05:13 +0000] [19414] [ERROR] Worker (pid:19523) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:05:13 +0000] [19414] [ERROR] Worker (pid:19524) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:05:13 +0000] [19414] [ERROR] Worker (pid:19522) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:05:13 +0000] [19558] [INFO] Booting worker with pid: 19558
[2025-08-03 21:05:13 +0000] [19559] [INFO] Booting worker with pid: 19559
[2025-08-03 21:05:13 +0000] [19560] [INFO] Booting worker with pid: 19560
[2025-08-03 21:05:13 +0000] [19561] [INFO] Booting worker with pid: 19561
[2025-08-03 21:05:43 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19558)
[2025-08-03 21:05:43 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19559)
[2025-08-03 21:05:43 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19560)
[2025-08-03 21:05:43 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19561)
[2025-08-03 21:05:44 +0000] [19414] [ERROR] Worker (pid:19558) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:05:44 +0000] [19414] [ERROR] Worker (pid:19559) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:05:44 +0000] [19414] [ERROR] Worker (pid:19560) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:05:44 +0000] [19414] [ERROR] Worker (pid:19561) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:05:44 +0000] [19587] [INFO] Booting worker with pid: 19587
[2025-08-03 21:05:45 +0000] [19588] [INFO] Booting worker with pid: 19588
[2025-08-03 21:05:45 +0000] [19589] [INFO] Booting worker with pid: 19589
[2025-08-03 21:05:45 +0000] [19590] [INFO] Booting worker with pid: 19590
[2025-08-03 21:06:15 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19587)
[2025-08-03 21:06:15 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19588)
[2025-08-03 21:06:15 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19589)
[2025-08-03 21:06:15 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19590)
[2025-08-03 21:06:16 +0000] [19414] [ERROR] Worker (pid:19587) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:06:16 +0000] [19414] [ERROR] Worker (pid:19588) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:06:16 +0000] [19414] [ERROR] Worker (pid:19589) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:06:16 +0000] [19414] [ERROR] Worker (pid:19590) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:06:16 +0000] [19619] [INFO] Booting worker with pid: 19619
[2025-08-03 21:06:16 +0000] [19620] [INFO] Booting worker with pid: 19620
[2025-08-03 21:06:16 +0000] [19621] [INFO] Booting worker with pid: 19621
[2025-08-03 21:06:16 +0000] [19622] [INFO] Booting worker with pid: 19622
[2025-08-03 21:06:46 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19619)
[2025-08-03 21:06:46 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19620)
[2025-08-03 21:06:46 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19621)
[2025-08-03 21:06:46 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19622)
[2025-08-03 21:06:47 +0000] [19414] [ERROR] Worker (pid:19620) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:06:47 +0000] [19414] [ERROR] Worker (pid:19621) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:06:47 +0000] [19414] [ERROR] Worker (pid:19622) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:06:48 +0000] [19414] [ERROR] Worker (pid:19619) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:06:48 +0000] [19656] [INFO] Booting worker with pid: 19656
[2025-08-03 21:06:48 +0000] [19655] [INFO] Booting worker with pid: 19655
[2025-08-03 21:06:48 +0000] [19654] [INFO] Booting worker with pid: 19654
[2025-08-03 21:06:48 +0000] [19657] [INFO] Booting worker with pid: 19657
[2025-08-03 21:07:18 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19654)
[2025-08-03 21:07:18 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19655)
[2025-08-03 21:07:18 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19656)
[2025-08-03 21:07:18 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19657)
[2025-08-03 21:07:19 +0000] [19414] [ERROR] Worker (pid:19655) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:07:19 +0000] [19414] [ERROR] Worker (pid:19656) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:07:19 +0000] [19414] [ERROR] Worker (pid:19657) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:07:19 +0000] [19414] [ERROR] Worker (pid:19654) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:07:19 +0000] [19685] [INFO] Booting worker with pid: 19685
[2025-08-03 21:07:19 +0000] [19686] [INFO] Booting worker with pid: 19686
[2025-08-03 21:07:19 +0000] [19687] [INFO] Booting worker with pid: 19687
[2025-08-03 21:07:19 +0000] [19688] [INFO] Booting worker with pid: 19688
[2025-08-03 21:07:49 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19685)
[2025-08-03 21:07:50 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19686)
[2025-08-03 21:07:50 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19687)
[2025-08-03 21:07:50 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19688)
[2025-08-03 21:07:51 +0000] [19414] [ERROR] Worker (pid:19685) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:07:51 +0000] [19414] [ERROR] Worker (pid:19686) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:07:51 +0000] [19414] [ERROR] Worker (pid:19687) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:07:51 +0000] [19414] [ERROR] Worker (pid:19688) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:07:51 +0000] [19714] [INFO] Booting worker with pid: 19714
[2025-08-03 21:07:51 +0000] [19715] [INFO] Booting worker with pid: 19715
[2025-08-03 21:07:51 +0000] [19716] [INFO] Booting worker with pid: 19716
[2025-08-03 21:07:51 +0000] [19717] [INFO] Booting worker with pid: 19717
[2025-08-03 21:08:21 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19714)
[2025-08-03 21:08:21 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19715)
[2025-08-03 21:08:21 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19716)
[2025-08-03 21:08:21 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19717)
[2025-08-03 21:08:22 +0000] [19414] [ERROR] Worker (pid:19714) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:08:22 +0000] [19414] [ERROR] Worker (pid:19715) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:08:22 +0000] [19414] [ERROR] Worker (pid:19716) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:08:22 +0000] [19414] [ERROR] Worker (pid:19717) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:08:22 +0000] [19741] [INFO] Booting worker with pid: 19741
[2025-08-03 21:08:22 +0000] [19742] [INFO] Booting worker with pid: 19742
[2025-08-03 21:08:22 +0000] [19743] [INFO] Booting worker with pid: 19743
[2025-08-03 21:08:22 +0000] [19744] [INFO] Booting worker with pid: 19744
[2025-08-03 21:08:53 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19741)
[2025-08-03 21:08:53 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19742)
[2025-08-03 21:08:53 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19743)
[2025-08-03 21:08:53 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19744)
[2025-08-03 21:08:54 +0000] [19414] [ERROR] Worker (pid:19742) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:08:54 +0000] [19414] [ERROR] Worker (pid:19743) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:08:54 +0000] [19414] [ERROR] Worker (pid:19744) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:08:54 +0000] [19414] [ERROR] Worker (pid:19741) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:08:54 +0000] [19776] [INFO] Booting worker with pid: 19776
[2025-08-03 21:08:54 +0000] [19775] [INFO] Booting worker with pid: 19775
[2025-08-03 21:08:54 +0000] [19777] [INFO] Booting worker with pid: 19777
[2025-08-03 21:08:54 +0000] [19778] [INFO] Booting worker with pid: 19778
[2025-08-03 21:09:24 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19775)
[2025-08-03 21:09:24 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19776)
[2025-08-03 21:09:24 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19777)
[2025-08-03 21:09:24 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19778)
[2025-08-03 21:09:25 +0000] [19414] [ERROR] Worker (pid:19775) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:09:25 +0000] [19414] [ERROR] Worker (pid:19776) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:09:25 +0000] [19414] [ERROR] Worker (pid:19777) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:09:25 +0000] [19414] [ERROR] Worker (pid:19778) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:09:25 +0000] [19805] [INFO] Booting worker with pid: 19805
[2025-08-03 21:09:25 +0000] [19804] [INFO] Booting worker with pid: 19804
[2025-08-03 21:09:25 +0000] [19806] [INFO] Booting worker with pid: 19806
[2025-08-03 21:09:25 +0000] [19807] [INFO] Booting worker with pid: 19807
[2025-08-03 21:09:56 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19804)
[2025-08-03 21:09:56 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19805)
[2025-08-03 21:09:56 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19806)
[2025-08-03 21:09:56 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19807)
[2025-08-03 21:09:57 +0000] [19414] [ERROR] Worker (pid:19806) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:09:57 +0000] [19414] [ERROR] Worker (pid:19807) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:09:57 +0000] [19414] [ERROR] Worker (pid:19805) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:09:57 +0000] [19414] [ERROR] Worker (pid:19804) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:09:57 +0000] [19846] [INFO] Booting worker with pid: 19846
[2025-08-03 21:09:57 +0000] [19845] [INFO] Booting worker with pid: 19845
[2025-08-03 21:09:57 +0000] [19844] [INFO] Booting worker with pid: 19844
[2025-08-03 21:09:57 +0000] [19847] [INFO] Booting worker with pid: 19847
[2025-08-03 21:10:27 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19844)
[2025-08-03 21:10:27 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19845)
[2025-08-03 21:10:27 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19846)
[2025-08-03 21:10:27 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19847)
[2025-08-03 21:10:28 +0000] [19414] [ERROR] Worker (pid:19845) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:10:28 +0000] [19414] [ERROR] Worker (pid:19846) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:10:28 +0000] [19414] [ERROR] Worker (pid:19847) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:10:28 +0000] [19414] [ERROR] Worker (pid:19844) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:10:28 +0000] [19881] [INFO] Booting worker with pid: 19881
[2025-08-03 21:10:28 +0000] [19882] [INFO] Booting worker with pid: 19882
[2025-08-03 21:10:28 +0000] [19883] [INFO] Booting worker with pid: 19883
[2025-08-03 21:10:28 +0000] [19884] [INFO] Booting worker with pid: 19884
[2025-08-03 21:10:59 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19881)
[2025-08-03 21:10:59 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19882)
[2025-08-03 21:10:59 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19883)
[2025-08-03 21:10:59 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19884)
[2025-08-03 21:11:00 +0000] [19414] [ERROR] Worker (pid:19881) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:11:00 +0000] [19414] [ERROR] Worker (pid:19884) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:11:00 +0000] [19414] [ERROR] Worker (pid:19883) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:11:00 +0000] [19414] [ERROR] Worker (pid:19882) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:11:00 +0000] [19909] [INFO] Booting worker with pid: 19909
[2025-08-03 21:11:00 +0000] [19910] [INFO] Booting worker with pid: 19910
[2025-08-03 21:11:00 +0000] [19911] [INFO] Booting worker with pid: 19911
[2025-08-03 21:11:00 +0000] [19912] [INFO] Booting worker with pid: 19912
[2025-08-03 21:11:30 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19909)
[2025-08-03 21:11:30 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19910)
[2025-08-03 21:11:30 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19911)
[2025-08-03 21:11:30 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19912)
[2025-08-03 21:11:31 +0000] [19414] [ERROR] Worker (pid:19910) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:11:31 +0000] [19414] [ERROR] Worker (pid:19911) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:11:31 +0000] [19414] [ERROR] Worker (pid:19912) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:11:31 +0000] [19414] [ERROR] Worker (pid:19909) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:11:31 +0000] [19938] [INFO] Booting worker with pid: 19938
[2025-08-03 21:11:31 +0000] [19939] [INFO] Booting worker with pid: 19939
[2025-08-03 21:11:31 +0000] [19940] [INFO] Booting worker with pid: 19940
[2025-08-03 21:11:32 +0000] [19941] [INFO] Booting worker with pid: 19941
[2025-08-03 21:12:02 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19938)
[2025-08-03 21:12:02 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19939)
[2025-08-03 21:12:02 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19940)
[2025-08-03 21:12:02 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19941)
[2025-08-03 21:12:03 +0000] [19414] [ERROR] Worker (pid:19939) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:12:03 +0000] [19414] [ERROR] Worker (pid:19941) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:12:03 +0000] [19414] [ERROR] Worker (pid:19940) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:12:03 +0000] [19414] [ERROR] Worker (pid:19938) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:12:03 +0000] [19967] [INFO] Booting worker with pid: 19967
[2025-08-03 21:12:03 +0000] [19968] [INFO] Booting worker with pid: 19968
[2025-08-03 21:12:03 +0000] [19969] [INFO] Booting worker with pid: 19969
[2025-08-03 21:12:03 +0000] [19970] [INFO] Booting worker with pid: 19970
[2025-08-03 21:12:33 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19967)
[2025-08-03 21:12:33 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19968)
[2025-08-03 21:12:33 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19969)
[2025-08-03 21:12:33 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19970)
[2025-08-03 21:12:34 +0000] [19414] [ERROR] Worker (pid:19968) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:12:34 +0000] [19414] [ERROR] Worker (pid:19969) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:12:34 +0000] [19414] [ERROR] Worker (pid:19970) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:12:34 +0000] [19414] [ERROR] Worker (pid:19967) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:12:34 +0000] [19993] [INFO] Booting worker with pid: 19993
[2025-08-03 21:12:34 +0000] [19994] [INFO] Booting worker with pid: 19994
[2025-08-03 21:12:34 +0000] [19995] [INFO] Booting worker with pid: 19995
[2025-08-03 21:12:35 +0000] [19996] [INFO] Booting worker with pid: 19996
[2025-08-03 21:13:05 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19993)
[2025-08-03 21:13:05 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19994)
[2025-08-03 21:13:05 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19995)
[2025-08-03 21:13:05 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:19996)
[2025-08-03 21:13:06 +0000] [19414] [ERROR] Worker (pid:19994) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:13:06 +0000] [19414] [ERROR] Worker (pid:19995) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:13:06 +0000] [19414] [ERROR] Worker (pid:19996) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:13:06 +0000] [19414] [ERROR] Worker (pid:19993) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:13:06 +0000] [20024] [INFO] Booting worker with pid: 20024
[2025-08-03 21:13:06 +0000] [20025] [INFO] Booting worker with pid: 20025
[2025-08-03 21:13:06 +0000] [20026] [INFO] Booting worker with pid: 20026
[2025-08-03 21:13:06 +0000] [20027] [INFO] Booting worker with pid: 20027
[2025-08-03 21:13:36 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:20024)
[2025-08-03 21:13:36 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:20025)
[2025-08-03 21:13:36 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:20026)
[2025-08-03 21:13:36 +0000] [19414] [CRITICAL] WORKER TIMEOUT (pid:20027)
[2025-08-03 21:13:38 +0000] [19414] [ERROR] Worker (pid:20024) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:13:38 +0000] [19414] [ERROR] Worker (pid:20025) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:13:38 +0000] [19414] [ERROR] Worker (pid:20026) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:13:38 +0000] [19414] [ERROR] Worker (pid:20027) was sent SIGKILL! Perhaps out of memory?
[2025-08-03 21:13:38 +0000] [20053] [INFO] Booting worker with pid: 20053
[2025-08-03 21:13:38 +0000] [20054] [INFO] Booting worker with pid: 20054
[2025-08-03 21:13:38 +0000] [20055] [INFO] Booting worker with pid: 20055
[2025-08-03 21:13:38 +0000] [20056] [INFO] Booting worker with pid: 20056
[2025-08-03 21:13:57 +0000] [19414] [INFO] Handling signal: term
[2025-08-03 21:14:20 +0000] [20055] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/cursos/wsgi.py", line 16, in <module>
    init_app()
  File "/home/ubuntu/cursos/app.py", line 176, in init_app
    init_routes(app)
  File "/home/ubuntu/cursos/routes/__init__.py", line 7, in init_routes
    AuthRoutes(app)
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 14, in __init__
    self.init_routes()
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 17, in init_routes
    @self.app.route('/register', methods=['GET', 'POST'])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 364, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 44, in wrapper_func
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/app.py", line 659, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: register
[2025-08-03 21:14:20 +0000] [20056] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/cursos/wsgi.py", line 16, in <module>
    init_app()
  File "/home/ubuntu/cursos/app.py", line 176, in init_app
    init_routes(app)
  File "/home/ubuntu/cursos/routes/__init__.py", line 7, in init_routes
    AuthRoutes(app)
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 14, in __init__
    self.init_routes()
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 17, in init_routes
    @self.app.route('/register', methods=['GET', 'POST'])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 364, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 44, in wrapper_func
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/app.py", line 659, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: register
[2025-08-03 21:14:20 +0000] [20055] [INFO] Worker exiting (pid: 20055)
[2025-08-03 21:14:20 +0000] [20056] [INFO] Worker exiting (pid: 20056)
[2025-08-03 21:14:20 +0000] [20054] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/cursos/wsgi.py", line 16, in <module>
    init_app()
  File "/home/ubuntu/cursos/app.py", line 176, in init_app
    init_routes(app)
  File "/home/ubuntu/cursos/routes/__init__.py", line 7, in init_routes
    AuthRoutes(app)
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 14, in __init__
    self.init_routes()
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 17, in init_routes
    @self.app.route('/register', methods=['GET', 'POST'])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 364, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 44, in wrapper_func
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/app.py", line 659, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: register
[2025-08-03 21:14:20 +0000] [20054] [INFO] Worker exiting (pid: 20054)
[2025-08-03 21:14:27 +0000] [19414] [ERROR] Worker (pid:20056) exited with code 3
[2025-08-03 21:14:33 +0000] [20053] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/cursos/wsgi.py", line 16, in <module>
    init_app()
  File "/home/ubuntu/cursos/app.py", line 176, in init_app
    init_routes(app)
  File "/home/ubuntu/cursos/routes/__init__.py", line 7, in init_routes
    AuthRoutes(app)
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 14, in __init__
    self.init_routes()
  File "/home/ubuntu/cursos/routes/auth_routes.py", line 17, in init_routes
    @self.app.route('/register', methods=['GET', 'POST'])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 364, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 44, in wrapper_func
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cursos/venv/lib/python3.12/site-packages/flask/sansio/app.py", line 659, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: register
[2025-08-03 21:14:33 +0000] [20053] [INFO] Worker exiting (pid: 20053)
[2025-08-03 18:53:07 -0400] [37126] [INFO] Starting gunicorn 23.0.0
[2025-08-03 18:53:07 -0400] [37126] [INFO] Listening at: http://127.0.0.1:8000 (37126)
[2025-08-03 18:53:07 -0400] [37126] [INFO] Using worker: sync
[2025-08-03 18:53:07 -0400] [37126] [ERROR] Unhandled exception in main loop
Traceback (most recent call last):
  File "/Users/emerson/opt/anaconda3/lib/python3.9/site-packages/gunicorn/arbiter.py", line 201, in run
    self.manage_workers()
  File "/Users/emerson/opt/anaconda3/lib/python3.9/site-packages/gunicorn/arbiter.py", line 570, in manage_workers
    self.spawn_workers()
  File "/Users/emerson/opt/anaconda3/lib/python3.9/site-packages/gunicorn/arbiter.py", line 641, in spawn_workers
    self.spawn_worker()
  File "/Users/emerson/opt/anaconda3/lib/python3.9/site-packages/gunicorn/arbiter.py", line 588, in spawn_worker
    worker = self.worker_class(self.worker_age, self.pid, self.LISTENERS,
  File "/Users/emerson/opt/anaconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 65, in __init__
    self.tmp = WorkerTmp(cfg)
  File "/Users/emerson/opt/anaconda3/lib/python3.9/site-packages/gunicorn/workers/workertmp.py", line 22, in __init__
    raise RuntimeError("%s doesn't exist. Can't create workertmp." % fdir)
RuntimeError: /dev/shm doesn't exist. Can't create workertmp.
[2025-08-03 18:53:56 -0400] [38049] [INFO] Starting gunicorn 23.0.0
[2025-08-03 18:53:56 -0400] [38049] [INFO] Listening at: http://127.0.0.1:8000 (38049)
[2025-08-03 18:53:56 -0400] [38049] [INFO] Using worker: sync
[2025-08-03 18:53:56 -0400] [38049] [ERROR] Unhandled exception in main loop
Traceback (most recent call last):
  File "/Users/emerson/Desktop/Todo_Mac/proyectos_python/venta_cursos_pagos/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 201, in run
    self.manage_workers()
  File "/Users/emerson/Desktop/Todo_Mac/proyectos_python/venta_cursos_pagos/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 570, in manage_workers
    self.spawn_workers()
  File "/Users/emerson/Desktop/Todo_Mac/proyectos_python/venta_cursos_pagos/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 641, in spawn_workers
    self.spawn_worker()
  File "/Users/emerson/Desktop/Todo_Mac/proyectos_python/venta_cursos_pagos/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 588, in spawn_worker
    worker = self.worker_class(self.worker_age, self.pid, self.LISTENERS,
  File "/Users/emerson/Desktop/Todo_Mac/proyectos_python/venta_cursos_pagos/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 65, in __init__
    self.tmp = WorkerTmp(cfg)
  File "/Users/emerson/Desktop/Todo_Mac/proyectos_python/venta_cursos_pagos/venv/lib/python3.9/site-packages/gunicorn/workers/workertmp.py", line 22, in __init__
    raise RuntimeError("%s doesn't exist. Can't create workertmp." % fdir)
RuntimeError: /dev/shm doesn't exist. Can't create workertmp.
[2025-08-03 18:55:05 -0400] [39926] [INFO] Starting gunicorn 23.0.0
[2025-08-03 18:55:05 -0400] [39926] [INFO] Listening at: http://127.0.0.1:8000 (39926)
[2025-08-03 18:55:05 -0400] [39926] [INFO] Using worker: sync
[2025-08-03 18:55:05 -0400] [39926] [ERROR] Unhandled exception in main loop
Traceback (most recent call last):
  File "/Users/emerson/Desktop/Todo_Mac/proyectos_python/venta_cursos_pagos/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 201, in run
    self.manage_workers()
  File "/Users/emerson/Desktop/Todo_Mac/proyectos_python/venta_cursos_pagos/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 570, in manage_workers
    self.spawn_workers()
  File "/Users/emerson/Desktop/Todo_Mac/proyectos_python/venta_cursos_pagos/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 641, in spawn_workers
    self.spawn_worker()
  File "/Users/emerson/Desktop/Todo_Mac/proyectos_python/venta_cursos_pagos/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 588, in spawn_worker
    worker = self.worker_class(self.worker_age, self.pid, self.LISTENERS,
  File "/Users/emerson/Desktop/Todo_Mac/proyectos_python/venta_cursos_pagos/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 65, in __init__
    self.tmp = WorkerTmp(cfg)
  File "/Users/emerson/Desktop/Todo_Mac/proyectos_python/venta_cursos_pagos/venv/lib/python3.9/site-packages/gunicorn/workers/workertmp.py", line 22, in __init__
    raise RuntimeError("%s doesn't exist. Can't create workertmp." % fdir)
RuntimeError: /dev/shm doesn't exist. Can't create workertmp.
